version: '3.7'


services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=23q4RSDFSDFS

  web:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .docker-compose-env
    restart: always
    ports:
      - "3000:3000"