version: '3.7'


services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=23q4RSDFSDFS

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: web
    ports:
      - "8000:3000"